# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b0988e91e40395bb2b946444889c6f9560e578be2f87cbc14c343b123b87c4481c8dcc04e37897a09386558b35d88b3ca8d20e62647bc6e564a6e393b31b78e

test:
  secret_key_base: 079750ed62a8aedd6293a437d461fa14d01ee80682b66e4fe68079cd536baa339365c98eb0d822c791b55f71f0efe6644e6038657d5f1242607cabbe298756d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
